# Generated by Django 3.1 on 2020-08-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subs',
            name='admin_email',
            field=models.EmailField(default='admin_user@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='subs',
            name='random_key',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_1',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_2',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_3',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D')], default='', max_length=100),
        ),
    ]
