# Generated by Django 3.1 on 2020-08-17 16:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200817_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='question_1',
            field=models.CharField(choices=[('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D'), ('Option E', 'Option E'), ('Option F', 'Option F'), ('Option G', 'Option G'), ('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3'), ('Option 4', 'Option 4'), ('Option 5', 'Option 5')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_4',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D'), ('Option E', 'Option E'), ('Option F', 'Option F'), ('Option G', 'Option G'), ('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3'), ('Option 4', 'Option 4'), ('Option 5', 'Option 5')], default='', max_length=107),
        ),
    ]
