# Generated by Django 3.1 on 2020-08-18 01:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_subs_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subs',
            name='question_10',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subs',
            name='question_5',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D'), ('Option E', 'Option E'), ('Option F', 'Option F'), ('Option G', 'Option G'), ('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3'), ('Option 4', 'Option 4'), ('Option 5', 'Option 5')], default='', max_length=107),
        ),
        migrations.AddField(
            model_name='subs',
            name='question_6',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subs',
            name='question_7',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subs',
            name='question_8',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subs',
            name='question_9',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D')], default='', max_length=100),
        ),
    ]
