# Generated by Django 3.1 on 2020-08-18 01:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20200817_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='question_1',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Candidate A', 'Candidate A'), ('Candidate B', 'Candidate B'), ('Candidate C', 'Candidate C'), ('Candidate D', 'Candidate D')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_10',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Candidate A', 'Candidate A'), ('Candidate B', 'Candidate B'), ('Candidate C', 'Candidate C'), ('Candidate D', 'Candidate D')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_2',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Candidate A', 'Candidate A'), ('Candidate B', 'Candidate B'), ('Candidate C', 'Candidate C'), ('Candidate D', 'Candidate D')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_3',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Candidate A', 'Candidate A'), ('Candidate B', 'Candidate B'), ('Candidate C', 'Candidate C'), ('Candidate D', 'Candidate D')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_4',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Candidate A', 'Candidate A'), ('Candidate B', 'Candidate B'), ('Candidate C', 'Candidate C'), ('Candidate D', 'Candidate D'), ('Candidate E', 'Candidate E'), ('Candidate F', 'Candidate F'), ('Candidate G', 'Candidate G'), ('Candidate 1', 'Candidate 1'), ('Candidate 2', 'Candidate 2'), ('Candidate 3', 'Candidate 3'), ('Candidate 4', 'Candidate 4'), ('Candidate 5', 'Candidate 5')], default='', max_length=143),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_5',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Candidate A', 'Candidate A'), ('Candidate B', 'Candidate B'), ('Candidate C', 'Candidate C'), ('Candidate D', 'Candidate D'), ('Candidate E', 'Candidate E'), ('Candidate F', 'Candidate F'), ('Candidate G', 'Candidate G'), ('Candidate 1', 'Candidate 1'), ('Candidate 2', 'Candidate 2'), ('Candidate 3', 'Candidate 3'), ('Candidate 4', 'Candidate 4'), ('Candidate 5', 'Candidate 5')], default='', max_length=143),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_6',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Candidate A', 'Candidate A'), ('Candidate B', 'Candidate B'), ('Candidate C', 'Candidate C'), ('Candidate D', 'Candidate D')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_7',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Candidate A', 'Candidate A'), ('Candidate B', 'Candidate B'), ('Candidate C', 'Candidate C'), ('Candidate D', 'Candidate D')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_8',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Candidate A', 'Candidate A'), ('Candidate B', 'Candidate B'), ('Candidate C', 'Candidate C'), ('Candidate D', 'Candidate D')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_9',
            field=models.CharField(choices=[('Choose', 'Choose'), ('Candidate A', 'Candidate A'), ('Candidate B', 'Candidate B'), ('Candidate C', 'Candidate C'), ('Candidate D', 'Candidate D')], default='', max_length=100),
        ),
    ]
