# Generated by Django 3.1 on 2020-09-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200817_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs',
            name='phone_number',
        ),
    ]
