# Generated by Django 3.1 on 2020-09-18 04:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_subs_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='question_1',
            field=models.CharField(choices=[('Kanye West', 'Kanye West'), ('Joe Biden', 'Joe Biden'), ('Donald Trump', 'Donald Trump')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_10',
            field=models.CharField(choices=[('Wolf Blitzer', 'Wolf Blitzer'), ('Anderson Cooper', 'Anderson Cooper'), ('Chris Cuomo', 'Chris Cuomo')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_2',
            field=models.CharField(choices=[('Rodrigo Duterte', 'Rodrigo Duterte'), ('Leni Robredo', 'Leni Robredo'), ('Manny Pacquiao', 'Manny Pacquiao')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_3',
            field=models.CharField(choices=[('Sharon Cuneta', 'Sharon Cuneta'), ('Dawn Zulueta', 'Dawn Zulueta'), ('Gretchen Barreto', 'Gretchen Barreto')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_4',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Taylor Swift', 'Taylor Swift'), ('Beyonce', 'Beyonce'), ('Katy Perry', 'Katy Perry'), ('Britney Spears', 'Britney Spears'), ('Christina Aguilera', 'Christina Aguilera'), ('Jennifer Lopez', 'Jennifer Lopez'), ('Ariana Grande', 'Ariana Grande'), ('P!nk', 'P!nk')], default='', max_length=99),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_5',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Zach Amados', 'Zach Amados'), ('Rianna Talento', 'Rianna Talento'), ('Reinny Florido', 'Reinny Florido'), ('Ryan Robles', 'Ryan Robles')], default='', max_length=53),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_6',
            field=models.CharField(choices=[('George Washington', 'George Washington'), ('Thomas Jefferson', 'Thomas Jefferson'), ('Ulysses Grant', 'Ulysses Grant')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_7',
            field=models.CharField(choices=[('Sharon Cuneta', 'Sharon Cuneta'), ('Dawn Zulueta', 'Dawn Zulueta'), ('Gretchen Barreto', 'Gretchen Barreto')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_8',
            field=models.CharField(choices=[('Barack Obama', 'Barack Obama'), ('George Bush', 'George Bush'), ('Bill Clinton', 'Bill Clinton')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subs',
            name='question_9',
            field=models.CharField(choices=[('Mike Pence', 'Mike Pence'), ('Kamala Harris', 'Kamala Harris'), ('Bernie Saunders', 'Bernie Saunders')], default='', max_length=100),
        ),
    ]
