# Generated by Django 3.1 on 2020-08-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('slug', models.SlugField(max_length=250)),
                ('question_1', models.CharField(default='', max_length=100)),
                ('question_2', models.CharField(default='', max_length=100)),
                ('question_3', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
