# Generated by Django 3.1 on 2020-08-17 15:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Submission', '0002_sub_question_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='question_4',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Option A', 'Option A'), ('Option B', 'Option B'), ('Option C', 'Option C'), ('Option D', 'Option D')], default='', max_length=35),
        ),
    ]
